//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cbp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public int RequestTypeID { get; set; }
        public string Description { get; set; }
        public string Urgency { get; set; }
        public int CompanyID { get; set; }
        public string Contact { get; set; }
        public int ExecutorID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Executor Executor { get; set; }
        public virtual RequestType RequestType { get; set; }
    }
}
